name: Code Formatting Check

on:
  pull_request:
    branches: [ master ]

jobs:
  spotless-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Check formatting
        run: ./gradlew spotlessCheck